### ISSUE TITLE
Nothing is displayed for minikube PVCs

### ISSUE THREAD

**Issue by corneliusweig** [yashbhutwala/kubectl-df-pv#2]
I tried to test via

```
minikube start
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: some-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Mi
EOF
```

which automatically creates a PV, see `kubectl get pv`:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 STORAGECLASS   REASON   AGE
pvc-803939a0-13ca-11ea-b74d-0800279f5fff   2Mi        RWO            Delete           Bound    default/block-pvc     standard                2m57s
```

However, when running `kubectl df-pv` nothing is displayed.
